apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::xxxxxx-role/eksctl-cicd-demo-nodegroup-ng-1-NodeInstanceRole-
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::xxxxx:role/CodeBuildKubectlRole
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-19T12:37:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2177"
  uid: 0d1efb51-b85f-4436-8e4b-2727b671dbf9
