apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lb-dashboard
    app.kubernetes.io/instance: cicd-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: lb-dashboard
spec:
  selector:
    app: dashboard-deployment
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
